### ISSUE TITLE
Not pulling metrics if any of the node in the cluster down. 

### ISSUE THREAD

**Issue by shagad65** [Starttoaster/proxmox-exporter#35]
Hi, I have tried the helm chart, we have Kubernetes Prometheus operator running outside proxmox. Proxmox have single cluster with 6 nodes. 

Below is my values.yaml, 
----------------------------
replicaCount: 1

image:
  repository: ghcr.io/starttoaster/proxmox-exporter
  pullPolicy: IfNotPresent

  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
 
  log_level: 'debug'

  port: '8080'

  api_insecure: 'true'

  endpoints: 'https://hw-pve-cn01.example.com:8006,https://hw-pve-cn02.example.com:8006,https://hw-pve-cn03.example.com:8006'

  token: 'xxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxx'
  tokenID: 'xxxxxxxx@pam!exporter'

serviceMonitor:
  enabled: true
  additionalLabels: 
    release: 'dev-prom'
  annotations: {}
  namespaceSelector: {}

  targetLabels: []
  relabelings: []
  metricRelabelings: []

prometheusRule:
  enabled: true

serviceAccount:

  create: true

  annotations: {}
 
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

-------------------

Deployed and i am able to see metrics in browser if i port-forward the exporter service, also Prometheus target looks good. 

![image](https://github.com/Starttoaster/proxmox-exporter/assets/168561307/a57d5bee-f7c1-4671-b85e-2882523fff61)

So now i have shutdown one of the node in proxmox cluster, now below issues noticed, 

Promethues proxmox Target is down
In browser metrics not loading anymore (if i port-forward as before)
Below is the only error logs available in  exporter pod (debug mode) (hw-pve-cn04  is the node that i shutdown)
![image](https://github.com/Starttoaster/proxmox-exporter/assets/168561307/90447e9a-23a9-44e4-8b20-e47a9e63875e)

------
time=2024-04-30T14:36:00.598Z level=ERROR msg="failed making request to get node storage" node=hw-pve-cn04 error="Get \"https://hw-pve-cn04.example.com:8006/api2/json/nodes/hw-pve-cn04/storage\": dial tcp 172.22.4.23:8006: connect: connection timed out"
time=2024-04-30T14:36:04.694Z level=ERROR msg="failed making request to get node LXCs" node=hw-pve-cn04 error="Get \"https://hw-pve-cn04.example.com:8006/api2/json/nodes/hw-pve-cn04/lxc\": dial tcp 172.22.4.23:8006: connect: connection timed out"
time=2024-04-29T10:13:14.451Z level=ERROR msg="failed making request to get node LXCs" node=hw-pve-cn04 error=""
time=2024-04-29T10:13:15.892Z level=ERROR msg="failed making request to get node LXCs" node=hw-pve-cn04 error=""
time=2024-04-29T10:13:18.178Z level=DEBUG msg="proxmox request was found in cache for GetNodeCertificatesInfo" node=hw-pve-cn05
time=2024-04-30T14:36:05.364Z level=ERROR msg="failed making request to get node VMs" node=hw-pve-cn04 error=""
time=2024-04-30T14:36:06.374Z level=ERROR msg="failed making request to get node storage" node=hw-pve-cn04 error=""
time=2024-04-30T14:36:07.314Z level=ERROR msg="failed making request to get node VMs" node=hw-pve-cn04 error=""
time=2024-04-30T14:36:08.436Z level=ERROR msg="failed making request to get node storage" node=hw-pve-cn04 error=""
----------------
I tried shutdown different nodes, also tried to add all 6 nodes as endpoints in chart, but same issue persist. 
Again if i bring the node up, the issue is getting resolved. Any issue in my configuration? 
Thanks

**Comment by Starttoaster** [comment]
Thanks for the report! Last time I had tried turning off a Proxmox node the exporter still put out metrics for the remaining nodes, but I did add on concurrency for making those requests to PVE since then, so maybe something was broken there. I'll have more time to look into this a bit later, but I will try to reproduce and get a fix for that before the end of this weekend :)

**Comment by Starttoaster** [comment]
Thanks again for reporting! It was very easy to reproduce with your detailed report. 

While testing this exporter for node failures I usually disabled the pveproxy service on a node, and assumed that would simulate a node failure. I noted today that disabling the pveproxy service did not have the same effect as shutting down the whole node for the purposes of testing this :smile:

If you pull the newest version of the `:latest` image, or use the `:v0.1.2` tag, they should contain the fix from the linked Pull Request.

**Comment by shagad65** [comment]
Thanks a bunch for the fix!!

We tried v0.1.2 and noticed a lot more improvement. However, now the Prometheus target is intermittently failing. We shut down one of the endpoints, and the target was down for 3-4 minutes before coming back up. After a few minutes, we observed that the target repeatedly goes offline and then comes back online. We tried curl the metrics path and noticed that curl takes more time intermittently to fetch the metrics. When all endpoints are up, curl is super-fast on all requests. Could this be because requests are still being sent to the endpoint that is down?

**Comment by Starttoaster** [comment]
Hm, that is an interesting problem. I assume Prometheus is setting a short request timeout when reaching out to the exporter. When loading the metrics endpoint, the first API request that gets made to Proxmox is to list all nodes in the cluster, which also gets their current up/down status. I did also notice that this first request is slower when a node is down. I think I'll need to put that request in its own goroutine so that the metric server just gets it from cache if it's too slow to respond for Prometheus to scrape it. I'll see if I can get that fix in later this evening 🙂

**Comment by Starttoaster** [comment]
@shagad65 I put out a new update that I believe addresses this. The problem with the exporter loading slowly when a node was down was actually caused by waiting for requests to time out against down Proxmox servers, which I was able to solve locally by implementing temporary "bans" on the clients when a request fails to a given Proxmox server. 

I think the way this client ban is implemented here would mitigate the issue for you. On the first request to a down Proxmox server, the client would be temporarily "banned" and only unbanned after a goroutine loop is able to make a successful request to it. The first time that a client is discovered to potentially be down, Prometheus might still hit its scrape interval timeout of 10 seconds. But subsequent exporter requests should be significantly faster. So you might see a small metrics gap when a node goes down, and then the metrics should start coming back in again once the down client is banned.

**Comment by shagad65** [comment]
Thank you @Starttoaster for the quick fix. 

With this fix the intermittent target unstable issue is resolved and looks good. Only seeing a small gap (2-3 min) in metrics at the time of node down which can be ignorable I think. 
One more quick question before i close this issue, is there any other Grafana dashboard available which we can see the node wise metrics? currently it is cluster wise. 
Thanks again.

**Comment by Starttoaster** [comment]
All the metrics this exporter currently exports gets displayed in the provided grafana dashboard. What would you like to see in a node-specific dashboard?

**Comment by shagad65** [comment]
Thank you, will try node exporter.
