### ISSUE TITLE
cannot unmarshal string into Go struct field GetNodeDisksListData.data.rpm of type int

### ISSUE THREAD

**Issue by ShiftyMcCool** [Starttoaster/proxmox-exporter#56]
Hello! I'm attempting to set up monitoring on my single-node homelab and am having trouble keeping this service running. When it first starts up, i'm able to see the exported data ONCE by going to the `/metrics` route.  After that, the container logs show this: 

```
time=2024-09-16T11:45:44.785Z level=INFO msg="Starting server" port=8080
time=2024-09-16T11:46:00.033Z level=ERROR msg="failed making request to get node disks" node=it-clowd-pve error="json: cannot unmarshal string into Go struct field GetNodeDisksListData.data.rpm of type int"
time=2024-09-16T11:46:00.033Z level=ERROR msg="failed making request to get node certificates" node=it-clowd-pve error="request to get node certificates was not successful. It's possible all clients are banned"
time=2024-09-16T11:46:00.033Z level=ERROR msg="failed making request to get node status" node=it-clowd-pve error="request to get node status was not successful. It's possible all clients are banned"
time=2024-09-16T11:46:00.166Z level=ERROR msg="failed making request to get node disks" node=it-clowd-pve error="request to get node disks was not successful. It's possible all clients are banned"
time=2024-09-16T11:46:00.166Z level=ERROR msg="failed making request to get node certificates" node=it-clowd-pve error="request to get node certificates was not successful. It's possible all clients are banned"
time=2024-09-16T11:46:00.166Z level=ERROR msg="failed making request to get node status" node=it-clowd-pve error="request to get node status was not successful. It's possible all clients are banned"
```

Seems that a data type may have changed? I saw another similar issue on this repo for `GetNodeLxcData.data.vmid` and an update to this app fixed it.

I am running PVE 8.2.4 and the latest release of this image. Let me know if you want any other info from me.  Thanks!

EDIT:

Looks like this may be the offending bit in `go-proxmox`? I'd submit a PR but seems like a bit of setup to test this 😛 

```
// GetNodeDisksListData contains data of disks from a GetNodeDisksList response
type GetNodeDisksListData struct {
	ByIDLink     string `json:"by_id_link"`
	DevPath      string `json:"devpath"`
	GPT          int    `json:"gpt"`
	Health       string `json:"health"`
	Model        string `json:"model"`
	RPM          int    `json:"rpm"`
	Serial       string `json:"serial"`
	Size         int    `json:"size"`
	Type         string `json:"type"`
	Used         string `json:"used"`
	Vendor       string `json:"vendor"`
	WWN          string `json:"wwn"`
	Bluestore    int    `json:"bluestore,omitempty"`
	OSDEncrypted int    `json:"osdencrypted,omitempty"`
}
```

**Comment by Starttoaster** [comment]
Thanks for reporting! Based on the error, it does sound like from your error output that they may have changed it from an integer to a string. I'll check this out in my clusters in a bit to reproduce, I should be close to 8.2.4, but since I'm not getting this error I'm assuming I'm a point release or two behind on PVE.

**Comment by Starttoaster** [comment]
Oddly, I cannot reproduce from PVE 8.2.4. Can you tell me more about your disks? Maybe it's specific to a type of disk. The output of the following curl could help too:
```
curl -k -X GET "https://<your-node-IP>:8006/api2/json/nodes/<your-node-name>/disks/list" -H 'Authorization: PVEAPIToken=<token-id>=<token-secret>'
```
Making sure to fill in the values between the carrots there for node IP, node name, token ID, and token secret. Did a glance through mine, and don't see anything scary/secretive. My RPM fields just show up as `"rpm":0,` in the json output, which would be an integer value as the API library currently identifies it. My cluster is on `pve-manager/8.2.4/faa83925c9641325 (running kernel: 6.8.8-4-pve)`

**Comment by ShiftyMcCool** [comment]
Maybe i'm the only dum-dum using HDD instead of SSD for disks in a Proxmox node? Looks like the issue is with any non-zero value to that property:
```
{
  "data": [
    {
      "devpath": "/dev/nvme0n1",
      "wwn": "eui.ace42e000a06be6a2ee4ac0000000001",
      "serial": "KS01N4365124Y1I4D",
      "by_id_link": "/dev/disk/by-id/nvme-SK_hynix_PC601_HFS512GD9TNG-L2A0A_KS01N4365124Y1I4D_1",
      "size": 512110190592,
      "used": "BIOS boot",
      "osdid": -1,
      "rpm": 0,
      "wearout": 99,
      "gpt": 1,
      "osdid-list": null,
      "health": "PASSED",
      "model": "SK hynix PC601 HFS512GD9TNG-L2A0A",
      "vendor": "unknown",
      "type": "nvme"
    },
    {
      "osdid": -1,
      "rpm": "5400",
      "serial": "ZDZS3PPR",
      "by_id_link": "/dev/disk/by-id/ata-ST2000LM007-1R8174_ZDZS3PPR",
      "size": 2000398934016,
      "used": "LVM",
      "devpath": "/dev/sda",
      "wwn": "0x5000c500e8b0009b",
      "type": "hdd",
      "vendor": "ATA     ",
      "health": "PASSED",
      "model": "ST2000LM007-1R8174",
      "gpt": 0,
      "osdid-list": null,
      "wearout": "N/A"
    },
    {
      "model": "WDC_WD50NDZW-11BCSS1",
      "health": "PASSED",
      "vendor": "WD      ",
      "type": "hdd",
      "wearout": "N/A",
      "osdid-list": null,
      "gpt": 1,
      "by_id_link": "/dev/disk/by-id/ata-WDC_WD50NDZW-11BCSS1_WD-WX32D24JRRYA",
      "size": 5000947302400,
      "used": "ZFS",
      "serial": "WD-WX32D24JRRYA",
      "rpm": "4800",
      "osdid": -1,
      "wwn": "0x50014ee2165026fb",
      "devpath": "/dev/sdb"
    },
    {
      "rpm": "4800",
      "osdid": -1,
      "by_id_link": "/dev/disk/by-id/ata-WDC_WD50NDZW-11BCSS1_WD-WX92D53ARAS6",
      "size": 5000947302400,
      "used": "ext4",
      "serial": "WD-WX92D53ARAS6",
      "wwn": "0x50014ee26b2a1db0",
      "devpath": "/dev/sdc",
      "type": "hdd",
      "vendor": "WD      ",
      "model": "WDC_WD50NDZW-11BCSS1",
      "health": "PASSED",
      "osdid-list": null,
      "gpt": 1,
      "wearout": "N/A"
    },
    {
      "type": "hdd",
      "vendor": "WD      ",
      "health": "PASSED",
      "model": "WDC_WD50NDZW-11BCSS0",
      "gpt": 1,
      "osdid-list": null,
      "wearout": "N/A",
      "osdid": -1,
      "rpm": "4800",
      "serial": "WD-WX72DA31MVPJ",
      "by_id_link": "/dev/disk/by-id/ata-WDC_WD50NDZW-11BCSS0_WD-WX72DA31MVPJ",
      "size": 5000947302400,
      "used": "ZFS",
      "devpath": "/dev/sdd",
      "wwn": "0x50014ee2c0d3632c"
    },
    {
      "size": 5000947302400,
      "used": "ZFS",
      "by_id_link": "/dev/disk/by-id/ata-WDC_WD50NDZW-11BCSS0_WD-WX32D24J1L8K",
      "serial": "WD-WX32D24J1L8K",
      "rpm": "4800",
      "osdid": -1,
      "wwn": "0x50014ee216515dbd",
      "devpath": "/dev/sde",
      "model": "WDC_WD50NDZW-11BCSS0",
      "health": "PASSED",
      "type": "hdd",
      "vendor": "WD      ",
      "wearout": "N/A",
      "osdid-list": null,
      "gpt": 1
    }
  ]
}
```

**Comment by Starttoaster** [comment]
> Maybe i'm the only dum-dum using HDD instead of SSD for disks in a Proxmox node?

:joy:
I don't think that's dumb at all. My HDDs are just in a NAS external to my Proxmox nodes, but I could definitely see the use for HDDs inside the cluster for slow tier ZFS or Ceph pools. I appreciate your Issue because it will help me improve proxmox-exporter and the client library for the Proxmox API for other users :)

If anything, Proxmox is kind of a dum-dum for using an integer to represent a zero value and a string for non-zero values 🤦 

Thank you so much for the output, I'll use this for the unit test in the proxmox client library to ensure HDD and SSD are supported. And I'll let you know here when I get a patch for this in. Should be no later than this weekend.

**Comment by ShiftyMcCool** [comment]
Ha! Thanks, good to know I'm not too out there 😄 

Yeah, not sure what they're thinking changing types like that based on value... I'll be interested to see the patch for this, I don't use go but I know it'd be a bit of a pain to handle that kind of thing in any other strongly-typed language I do know.

Thanks for looking into it!

**Comment by Starttoaster** [comment]
> it'd be a bit of a pain to handle that kind of thing in any other strongly-typed language I do know.
A bit. Luckily another field was already identified (as you pointed out) that can variably be an integer or string type, so a lot of the work for this was already done. 

But since you mentioned interest in seeing the patch:

This commit is the main thing that needed to change here, ignoring the test files of course: https://github.com/Starttoaster/go-proxmox/pull/6/commits/407008ab7bfc5e1e1921fab3ecab3e24a26489ae

In Go, the way you work around things like this is with a custom type, where I defined one like `type IntOrString string` and then created a custom "unmarshaller" function that implements the JSON marshal interface to handle JSON using that IntOrString type: https://github.com/Starttoaster/go-proxmox/blob/1f1c4595406a61e255c6c3e5f6b81506b2a23b91/types.go#L68

In that unmarshaller function, basically I'm trying to cast the data bytes as an integer, and if there's an error, I try to cast them as a string, and I return whichever one works (or an error if neither work.)

And then in this proxmox-exporter project I just need to update my pin of the go-proxmox library like this https://github.com/Starttoaster/proxmox-exporter/pull/58/files

**Comment by Starttoaster** [comment]
I'm releasing v0.2.3 which _should_ fix this issue. Thanks for pointing it out, and please let me know if the issue happens to persist or you find a new one :) I imagine it's not just a few places that Proxmox returns mismatched types depending on the environment.

**Comment by ShiftyMcCool** [comment]
Looks like that did it, thanks! Your project is a much better solution than the generally accepted one (imho). I'm happy to find out the dev is just as good. Cheers!
